# Generated by Django 2.1.3 on 2018-11-09 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura_pref', models.CharField(choices=[('c', '°C'), ('f', '°F')], default='c', max_length=1)),
                ('viento_pref', models.CharField(choices=[('kph', 'km/h'), ('mph', 'mph')], default='kph', max_length=3)),
                ('lluvia_pref', models.CharField(choices=[('mm', 'mm'), ('in', 'inch')], default='mm', max_length=2)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('modificado_el', models.DateTimeField(auto_now=True)),
                ('temperatura', models.DecimalField(decimal_places=3, max_digits=5)),
                ('viento', models.DecimalField(decimal_places=3, max_digits=6)),
                ('lluvia', models.DecimalField(decimal_places=3, max_digits=5)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro',
                'verbose_name_plural': 'registros',
            },
        ),
    ]
